### PR TITLE
Helm pathpattern support

### LINKED ISSUE #53: Helm chart does not support pathPattern
Hi all,

From what I can see there is currently no way of setting a pathPattern with the Helm chart? This would be quite handy for us, so if there is not a reason against it, I might can create a PR for this.

Cheers

### PR DESCRIPTION
**Pull request by ariksidney**
Adds support for pathpattern to the Helmchart.

Resolves #53

### CODE REVIEW

**Comment by ariksidney** [comment]
signed agreement

**Comment by geoff-coppertop** [comment]
Would this work to address #5? Would it be possible to add an example of providing a pattern that uses the metadata specified to the README?

**Comment by ariksidney** [comment]
I'm not entirely sure what's missing. With the pathPattern param it's possible to define a name pattern for the acutal folder on the nfs drive. Do you mean to just add an example to the Readme or the values.yaml on how this parameter works?

**Comment by geoff-coppertop** [comment]
I'm not sure whether the readme or values.yaml would be most appropriate.

**Comment by ariksidney** [comment]
Ah got it. I think the README explains it, do you think it should be clarified? So for example if you want your folders to be named `<pvc-namespace>/<pvc-name>`, you would set the pathPattern to $`{.PVC.namespace}-\${.PVC.name}`. This way you don't have the UID in the actual name.

**Comment by geoff-coppertop** [comment]
Ya if you could clarify with this example that'd be great!

**Comment by geoff-coppertop** [comment]
I have no authority but this lets me work around #5. LGTM

**Review by kmova — APPROVED** [review]
/lgtm

**Comment by kmova** [comment]
cc: @yonatankahana for another review of the helm chart changes.

**Pull request merged**
