### PR TITLE
Fixes Issue #172

### PR DESCRIPTION
**Pull request by tinguin**
Added option to set the volumeBindingMode for StorageClass

### CODE REVIEW

**Comment by gfnord** [comment]
Hi @ashishranjan738, please could you check the merge of this PR? Thanks buddy!

**Comment by tinguin** [comment]
Hi [yonatankahana](https://github.com/yonatankahana), [kmova](https://github.com/kmova), please have a look, would be great to get an approval for the code to be merged. Thank you!

**Comment by yonatankahana** [comment]
> Hi [yonatankahana](https://github.com/yonatankahana), [kmova](https://github.com/kmova), please have a look, would be great to get an approval for the code to be merged. Thank you!

Hi @tinguin,
please bump the charts `version` in `Chart.yaml` so merging the PR will trigger chart release with the changes.

**Comment by tinguin** [comment]
Hope i've done it right this time.

**Review by yonatankahana — APPROVED** [review]

**Pull request merged**
