### PR TITLE
adding kmova as approver

### PR DESCRIPTION
**Pull request by kmova**
Ref: https://github.com/kubernetes/org/issues/1744#issuecomment-604192447

### CODE REVIEW

**Comment by kmova** [comment]
@nikhita  - need help in checking what I might be missing here.

**Comment by mrbobbytables** [comment]
@kmova - you have not accepted your kubernetes-sigs org invite yet. It still lists it as pending.

**Comment by kmova** [comment]
Thanks @mrbobbytables! Found it.

**Pull request merged**
