### PR TITLE
Add arm64 support

### PR DESCRIPTION
**Pull request by codayblue**
This will resolve the issue I made earlier:  #11 

Let me know if I missed something or if I need to setup something. You can find the image I generated at quay.io/codayblue/nfs-subdir-external-provisioner-arm64

Then the other two were also generated and uploaded to quay.io/codayblue/nfs-subdir-external-provisioner and quay.io/codayblue/nfs-subdir-external-provisioner-arm

I tested against my aarch64 boards and was able to get it up and running. I am still testing some more but so far it is working.

### CODE REVIEW

**Comment by johanfleury** [comment]
Docker supports multi-arch images since a few versions, it might be better to build such an image rather than building a separate one or having a separate tag for arm.

See [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

**Comment by kmova** [comment]
@codayblue - are you working on the multi-arch build or shall I go ahead with reviewing this PR. 

One of the other tasks that we need to get done on this repo is to be able to automate the generation of images and push to gcr registry (similar to other sig-storage images)

**Comment by codayblue** [comment]
@kmova I am looking into the multi arch build. Was going to do that last week but well life happens sometimes lol. I should have sometime in the next couple days.

**Comment by codayblue** [comment]
@kmova so I got it working but I quickly discovered quay.io does something really weird with multiarch image manifests https://quay.io/repository/codayblue/nfs-subdir-external-provisioner?tab=history so might have to check out if GCR will do the same. I got it working with buildx but I had to install it because I run ubuntu and it does not come with it out of the box. Also I had to install qemu, qemu-user-static, and binfmt-support but sounds like docker for desktop on mac and windows comes with all this. I am not 100% sure how this gets deployed now. I can put up what changes I have in this branch or a new branch if you wanna compare them or not. There is another way to do the multiarch without buildx, I tried it earlier and failed a few times but after getting buildx working I realized I forgot to have qemu stuff ready on this box and not that I have it I assume it will work although might need more tweaking but I am fine with working on that.

**Comment by codayblue** [comment]
Threw it into another branch anyway just to have a backup that is working buy might need some touching up. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/compare/master...codayblue:multiarch?expand=1

**Comment by moikot** [comment]
How about building it using beautifully written [docker/build-push-action@v2](https://github.com/docker/build-push-action) GitHub action? Using something similar to [this](https://github.com/docker/build-push-action#handle-tags-and-labels) example it should be easy to add tags support and automate publishing too.

I've been using it successfully for building multiple multi-arch images, here is one example - [Dockerfile](https://github.com/moikot/basic-git-server/blob/master/Dockerfile) and [Build Action](https://github.com/moikot/basic-git-server/blob/master/.github/workflows/release.yml).

**Comment by moikot** [comment]
I forked this repo and set up the build using docker/build-push-action@v2 and a new Docker file. https://github.com/moikot/nfs-subdir-external-provisioner

The resulting images can be found here https://quay.io/repository/moikot/nfs-subdir-external-provisioner?tab=tags. The `edge` label is attached to every build from the `master` branch. The `latest` label, as well as semantic labels (e.g. `1`, `1.0`, and `1.0.0`), are attached to the builds associated with tagged commits. Pull requests should trigger builds but the resulting images are not pushed to the registry.

The approach proposed is acceptable, I can try to adjust the Makefile and prepare a PR.

**Comment by codayblue** [comment]
I thought quay was doing something weird when looking at the history and it saying the tag moved from hash to hash over and over for each arch. Though when you look at the tags they are handling it and has the label for each multiarch.

**Comment by moikot** [comment]
@codayblue , I might be wrong, but looking at quay's tagging history, I think they are trying to reflect the fact that a tag, in the case of tagging a manifest list (which must be used for multi-arch images), is attached to every manifest referenced, as well as to the list itself. So, in the case of three platforms, linux/amd64, linux/arm/v7, and linux/arm64, one should expect to see four records for every tag move - one for the manifest list and three for the individual manifests.

**Comment by codayblue** [comment]
> I forked this repo and set up the build using docker/build-push-action@v2 and a new Docker file. https://github.com/moikot/nfs-subdir-external-provisioner
> 
> The resulting images can be found here https://quay.io/repository/moikot/nfs-subdir-external-provisioner?tab=tags. The `edge` label is attached to every build from the `master` branch. The `latest` label, as well as semantic labels (e.g. `1`, `1.0`, and `1.0.0`), are attached to the builds associated with tagged commits. Pull requests should trigger builds but the resulting images are not pushed to the registry.
> 
> If the approach proposed is acceptable, I can try to adjust the Makefile and prepare a PR.

This solution IMO is cleaner and comes with the pipeline built into github. I checked and the login process can pretty much point at any registry.

**Comment by moikot** [comment]
Created PR #21, please review.

**Comment by codayblue** [comment]
Closing in favor of #21

**Pull request closed without merging**
