### PR TITLE
Rename master to main

### PR DESCRIPTION
**Pull request by ikarldasan**
**What this PR does / why we need it:**
Needed for https://github.com/kubernetes/k8s.io/issues/1597

**Which issue(s) this PR fixes (optional, using fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged):**
Needed for https://github.com/kubernetes/k8s.io/issues/1597

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by pohly** [comment]
/hold

"release-tools" should not be modified locally. The same change already went into csi-release-tools and will be copied from there.

**Comment by spiffxp** [comment]
Same question as https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/55#issuecomment-887196944

**Comment by spiffxp** [comment]
This repo is still showing up in cs.k8s.io as referencing the old links.  What needs to happen to pull in the update of csi-release-tools? Then I think we can close this out

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/144 which is basically https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/70 but for this repo

**Comment by spiffxp** [comment]
/close
superceded by https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/144

**Pull request closed without merging**
